### ISSUE TITLE
Parameter NW throws error

### ISSUE THREAD

**Issue by umbertones** [br-data/corona-divi-api#4]
While all other area parameters work, the NW throws an error:

https://europe-west3-brdata-corona.cloudfunctions.net/diviApi/query?area=NW&indicator=Patienten&filetype=csv

"error":"Query failed: Please check your area and indicator parameters"

Same with JSON.

**Comment by stekhn** [comment]
Thanks for heads up. I messed up the areaIds for Nordrhein-Westfalen. This should be fixed now: https://github.com/br-data/corona-divi-api/commit/c61da21af6bcff725f2c346b281f43afe60c82ad
