### ISSUE TITLE
Patientendaten nicht pausibel

### ISSUE THREAD

**Issue by maver2** [br-data/corona-divi-api#5]
Die von der API gelieferten Daten mit indicator=Patienten sind nicht plausibel: Die Werte für area=DE (Deutschland) müssten für jeden Tag die Summe aller Bundesländer ergeben.

Die Zahlenreihen für area=DE (Deutschland) und NW (Nordrhein-Westfalen) liefern  aber für jeden Tag die gleichen Werte. 

DE: https://europe-west3-brdata-corona.cloudfunctions.net/diviApi/query?area=DE&indicator=Patienten&filetype=csv
NW: https://europe-west3-brdata-corona.cloudfunctions.net/diviApi/query?area=NW&indicator=Patienten&filetype=csv

Getestet am 30.8.2021.

**Comment by ghost** [comment]
Confirmed. Luckily the problem only exists with NW.

Problem is in ``chart.json``. There we have same chardId for some ``NW`` and ``DE`` entries:

| chartId | indicator           | area                | areaId | same_charId |
|---------|---------------------|---------------------|--------|-------------|
| fStQ0   | Meldebereiche       | Nordrheim-Westfalen | NW     |             |
| i39qA   | Bettenanteil        | Nordrheim-Westfalen | NW     |             |
| mhKgW   | Betriebssituation   | Nordrheim-Westfalen | NW     |             |
| mhKgW   | Betriebssituation   | Deutschland         | DE     | !!!         |
| ovyiI   | Patienten           | Nordrheim-Westfalen | NW     |             |
| ovyiI   | Patienten           | Deutschland         | DE     | !!!         |
| RLWg1   | Bettenstatus        | Nordrheim-Westfalen | NW     |             |
| RLWg1   | Bettenstatus        | Deutschland         | DE     | !!!         |
| TjzQb   | Intensivkapazitäten | Nordrheim-Westfalen | NW     |             |
| TjzQb   | Intensivkapazitäten | Deutschland         | DE     | !!!         |
| TnXY1   | Meldebereiche       | Deutschland         | DE     |             |
| UIdqI   | Bettenanteil        | Deutschland         | DE     |             |

**Comment by ghost** [comment]
The URLs for Nordrhein-Westfalen are (different order! Source: https://www.intensivregister.de/#/aktuelle-lage/zeitreihen):

```
https://datawrapper.dwcdn.net/4cFYs/215/dataset.csv
https://datawrapper.dwcdn.net/Ya4yB/211/dataset.csv
https://datawrapper.dwcdn.net/fStQ0/215/dataset.csv
https://datawrapper.dwcdn.net/DMJcy/211/dataset.csv
https://datawrapper.dwcdn.net/i39qA/211/dataset.csv
```

While at it, you could also fix the typo in "Nordrhei**m**-Westfalen".
