### ISSUE TITLE
Request: Tagesaktuelle Werte gesondert ausgeben

### ISSUE THREAD

**Issue by monotonus** [br-data/corona-divi-api#8]
Wäre es möglich den tagesaktuellen Wert in einem fest definierten Platz, z.B. direkt am Anfang, zu hinterlegen, sodass eine JSON Abfrage immer statisch bleiben kann und nicht täglich hochgezählt werden muss?

**Comment by lor-enz** [comment]
Dazu ist keine Modifikation an der API nötig. Das lässt sich wunderbar im Code lösen. 
So mache ich es zumindest bei meinen Anfragen. 
Anfrage stellen und Liste erhalten. Von der Liste das letzte Element wählen, das ist immer das aktuellste Element.
